[package]
name = "rs-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
syn = { version = "2.0.67", features = ["full"] }
syn-serde = { version = "0.3.1", features = ["json"] }
